# Use the Ubuntu base image
FROM ubuntu:latest

# Set default shell during Docker image build to bash
SHELL ["/bin/bash", "-c"]

# Update and install dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    python3-tk \
    curl \
    vim \
    git \
    # Add other packages as needed
    && apt-get clean

# Set the working directory
WORKDIR /workspace

# Create and set up a virtual environment in /workspace/venv
RUN python3 -m venv /workspace/venv

# Install Python dependencies
COPY requirements.txt .
RUN /workspace/venv/bin/pip install --no-cache-dir -r requirements.txt
RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && \
    chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
    apt update && apt install gh -y

# Copy the rest of the project files into the container
COPY . .

# Set the default command to start a bash shell with the virtual environment activated
CMD ["/bin/bash", "-c", "source /workspace/venv/bin/activate && exec /bin/bash"]
